# User Settings

# Site Info
title: "bright"
description: "another minimalist Jekyll theme."
author: "Nathan Drake"
picture: "assets/images/profile.jpeg" # link to your picture goes here

# Site Settings
url: ""
baseurl: ""
permalink: "/:title:output_ext"

# Enable Google Analytics
# tracking_id: 'UA-XXXXXXXXXX'

# Add the links to your social media
fb_url: "https://facebook.com"
twitter_url: "https://twitter.com"
github_url: "https://github.com"
linkedin_url: "https://linkedin.com"
myemail: "myemail@example.com"

# Blog Settings
reading-time: true
paginate: 5
paginate_path: "/blog/page:num/"

# Build Settings
# markdown: kramdown
theme: bright

# Plugins
plugins:
  - jekyll-paginate
